#' Compare trajectory estimators
#'
#' Combines Omics Trajectory Signature assignments from two or more
#' `LongOmicsTraj` objects into a common table suitable for agreement and
#' consensus analyses.
#'
#' Each supplied object must contain OTS assignments generated by
#' `lot_map_to_ots()`. The original estimator column is replaced by the labels
#' supplied through `.names`, allowing results from different modelling
#' strategies to be compared directly.
#'
#' @param object A `LongOmicsTraj` object containing OTS assignments.
#' @param ... Additional `LongOmicsTraj` objects containing OTS assignments.
#' @param .names Optional character vector giving estimator labels. When
#'   omitted, labels of the form `"estimator_1"`, `"estimator_2"` and so on
#'   are used.
#'
#' @return An `S4Vectors::DataFrame` containing the combined OTS assignments
#'   and an `estimator` column identifying their source.
#'
#' @rdname lot_compare_estimators
#' @examples
#' data("lot_glucold_ots")
#'
#' ## For illustration, compare two stored trajectory analyses.
#' comparison <- lot_compare_estimators(
#'   lot_glucold_ots,
#'   lot_glucold_ots,
#'   .names = c(
#'     "analysis_1",
#'     "analysis_2"
#'   )
#' )
#'
#' comparison <- as.data.frame(comparison)
#'
#' table(
#'   comparison$estimator
#' )
#'
#' utils::head(
#'   comparison[
#'     ,
#'     c(
#'       "object_id",
#'       "group",
#'       "topology_label",
#'       "estimator"
#'     )
#'   ]
#' )
#' @export
methods::setMethod(
  "lot_compare_estimators",
  signature(
    object = "LongOmicsTraj"
  ),
  function(
    object,
    ...,
    .names = NULL
  ) {
    
    objects <- c(
      list(object),
      list(...)
    )
    
    valid_objects <- vapply(
      objects,
      function(current_object) {
        methods::is(
          current_object,
          "LongOmicsTraj"
        )
      },
      logical(1)
    )
    
    if (!all(valid_objects)) {
      stop(
        "All inputs must be `LongOmicsTraj` objects.",
        call. = FALSE
      )
    }
    
    if (length(objects) < 2L) {
      stop(
        "Provide at least two `LongOmicsTraj` objects.",
        call. = FALSE
      )
    }
    
    if (is.null(.names)) {
      .names <- paste0(
        "estimator_",
        seq_along(objects)
      )
    }
    
    if (
      !is.character(.names) ||
      length(.names) != length(objects) ||
      anyNA(.names) ||
      any(!nzchar(.names))
    ) {
      stop(
        "`.names` must contain one non-empty label for each object.",
        call. = FALSE
      )
    }
    
    if (anyDuplicated(.names)) {
      stop(
        "`.names` must contain unique estimator labels.",
        call. = FALSE
      )
    }
    
    ots_list <- Map(
      function(current_object, estimator_name) {
        
        ots_data <- as.data.frame(
          lot_ots(current_object)
        )
        
        if (nrow(ots_data) == 0L) {
          stop(
            "Each object must contain OTS assignments. ",
            "Run `lot_map_to_ots()` first.",
            call. = FALSE
          )
        }
        
        required_columns <- c(
          "object_id",
          "group",
          "topology_label"
        )
        
        missing_columns <- setdiff(
          required_columns,
          colnames(ots_data)
        )
        
        if (length(missing_columns) > 0L) {
          stop(
            "OTS results are missing required columns: ",
            paste(
              missing_columns,
              collapse = ", "
            ),
            call. = FALSE
          )
        }
        
        ots_data$estimator <- estimator_name
        
        ots_data
      },
      objects,
      .names
    )
    
    combined <- do.call(
      rbind,
      ots_list
    )
    
    rownames(combined) <- NULL
    
    S4Vectors::DataFrame(
      combined
    )
  }
)